name: Testing

on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches: [main]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.22'
        cache-dependency-path: "**/*.sum"
        check-latest: true

    - name: Run tests
      if: always()
      run: go test ./...

    - name: Run verbose tests
      if: always()
      run: go test -v ./...
